repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0  # Usa la última versión de ruff-pre-commit
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements-dev.in
        files: ^requirements/requirements-dev\.in$
        args: [--output-file=requirements/requirements-dev.txt, requirements/requirements-dev.in, --upgrade]
      - id: pip-compile
        name: pip-compile requirements-local.in
        files: ^requirements/requirements-local\.in$
        args: [--output-file=requirements/requirements-local.txt, requirements/requirements-local.in, --upgrade]
