[tool.ruff]
line-length = 79
target-version = "py311"

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "I", "TID252"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["TID252"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
    "integration: Tests que requieren configuración especial o infra como base de datos",
]
