FROM python:3.13.3-alpine

RUN apk add --no-cache \
    postgresql-dev

WORKDIR /var/www
COPY requirements/requirements-local.txt .
RUN pip install --no-cache-dir -r requirements-local.txt

COPY src/app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
