FROM python:3.13.10-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    libpq \
    postgresql-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    cargo

WORKDIR /var/www
COPY requirements/requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY src/app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
